name: Docker Image CI

on:
 push:
  branches: ['main']
env:
 PROJECT_ID: '${{ secrets.CLOUD_RUN_PROJECT_ID }}'
 REGION: us-central1
 REPO_NAME: portfolio
jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   # - name: Write a multi-line message
   # - uses: actions/checkout@v3
   # run: |
   #   echo This demo file shows a
   #   echo very basic and easy-to-understand workflow.

   - name: Google Auth
     id: auth
     uses: 'google-github-actions/auth@v0'
     with:
      credentials_json: '${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}'

   - name: Authorize Docker push
     run: gcloud auth configure-docker

   - name: Build and tag the docker image
     run: docker build . --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

   - name: Push the image to Google Container Registry
     run: docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

   - name: Deploy
     run: |-
      gloud run deploy $REPO_NAME \
      --region $REGION \
      --imgae gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
      --platform managed \
      --quiet

  # steps:
  #  - uses: actions/checkout@v2
  #  - name: Build the Docker image
  #    run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

# on:
#  push:
#   branches: ['main']
#  pull_request:
#   branches: ['main']

# jobs:
#  build:
#   runs-on: ubuntu-latest

#   steps:
#    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

# name: Portfolio CI/CD
# on:
#  branches: [main]
# env:
#  PROJECT_ID: '${{ secrets.CLOUD_RUN_PROJECT_ID }}'
#  REGION: us-central1
#  REPO_NAME: portfolio
# jobs:
#  build: null
#  name: Hello world
#  runs-on: ubuntu-latest
#  steps:
#   - uses: actions/checkout@v3
#   - name: Write a multi-line message
# run: |
#   echo This demo file shows a
#   echo very basic and easy-to-understand workflow.

#   # - name: Google Auth
#   # id: auth
#   # uses: 'google-github-actions/auth@v0'
#   # with:
#   #   credentials_json: '${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}'

#   # - name: Authorize Docker  push
#   # run: gcloud auth configure-docker

#   # - name: Build and tag the docker image
#   # run: docker build . --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

#   # - name: Push the image to Google Container Registry
#   # run: docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

#   # - name: Deploy
#   # run: |-
#   #     gloud run deploy $REPO_NAME \
#   #     --region $REGION \
#   #     --imgae gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
#   #     --platform managed \
#   #     --quiet
