name: Docker Image CI

on:
 push:
  branches: ['main']
env:
 PROJECT_ID: '${{ secrets.CLOUD_RUN_PROJECT_ID }}'
 REGION: us-central1
 REPO_NAME: portfolio
jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout
     uses: actions/checkout@v3

   - name: Google Auth
     id: auth
     uses: 'google-github-actions/auth@v0'
     with:
      credentials_json: '${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}'

   - name: Set up Cloud SDK
     uses: google-github-actions/setup-gcloud@v0

   - name: Authorize Docker push
     run: gcloud auth configure-docker

   - name: Build and tag the docker image
     run: docker build . --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

   - name: Push the image to Google Container Registry
     run: docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

   - name: Deploy
     run: |-
      gloud run deploy $REPO_NAME \
      --region $REGION \
      --imgae gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
      --platform managed \
      --quiet
